/**
 * CRM domain — built for high-ticket real estate, where a "lead" is worth
 * ₹1.2 Cr to ₹25 Cr+, the sales cycle runs months, and the money arrives in
 * tranches (token → agreement → installments → registration) rather than once.
 *
 * That shape drives three decisions the rest of the module depends on:
 *  - Budget is a *range* per lead, not a number: buyers state a band, and the
 *    grid has to filter on overlap, not equality.
 *  - Contacts and leads are separate records. One HNWI buys three units over
 *    four years; their KYC, net-worth band and transaction history belong to the
 *    person, not to any single enquiry.
 *  - Follow-ups are generated from state, not typed by hand. A site visit or a
 *    paid token implies a known sequence of obligations with statutory-ish
 *    deadlines, and forgetting one is how deals die.
 */

export type LeadStatus =
  | "new"
  | "contacted"
  | "site_visit_scheduled"
  | "negotiation"
  | "booking_token_paid"
  | "won"
  | "lost";

export type LeadSource =
  | "instagram"
  | "facebook"
  | "whatsapp"
  | "meta_ads"
  | "google_ads"
  | "portal_99acres"
  | "portal_magicbricks"
  | "portal_housing"
  | "referral"
  | "broker"
  | "walk_in"
  | "website";

export type KycStatus = "not_started" | "pending" | "verified" | "rejected";
export type HnwiTier = "none" | "affluent" | "hnwi" | "uhnwi";

export interface Broker {
  id: string;
  brandId: string;
  name: string;
  firm: string;
  phone: string;
  /** RERA agent registration — required to pay a commission legally in India. */
  reraId: string;
  commissionPct: number;
  leadsReferred: number;
  dealsClosed: number;
  rating: number;
  active: boolean;
}

export interface Lead {
  id: string;
  brandId: string;
  name: string;
  phone: string;
  email?: string;
  city: string;
  status: LeadStatus;
  /** Stated budget band, in rupees. */
  budgetMin: number;
  budgetMax: number;
  source: LeadSource;
  brokerId?: string;
  projectInterest: string;
  unitType: string;
  assignedTo: string;
  /** 0–100, computed by scoreLead() — never hand-entered. */
  score: number;
  isHNWI: boolean;
  kycStatus: KycStatus;
  contactId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  lastContactedAt?: string;
  siteVisitAt?: string;
  tokenPaidAt?: string;
  wonAt?: string;
  lostReason?: string;
  tags: string[];
}

export interface Transaction {
  id: string;
  contactId: string;
  project: string;
  unit: string;
  type: "booking_token" | "agreement" | "installment" | "registration" | "final_payment";
  amount: number;
  date: string;
  status: "paid" | "pending" | "overdue";
  mode: "neft" | "rtgs" | "cheque" | "upi" | "loan_disbursement";
  reference: string;
}

export interface CrmContact {
  id: string;
  brandId: string;
  name: string;
  phone: string;
  email?: string;
  city: string;
  type: "lead" | "customer" | "broker" | "investor";
  hnwiTier: HnwiTier;
  netWorthBand?: string;
  kycStatus: KycStatus;
  /** Which documents are actually on file — the reason KYC stalls. */
  kycDocs: string[];
  kycUpdatedAt?: string;
  occupation: string;
  company?: string;
  preferredLanguage: string;
  relationshipManager: string;
  lifetimeValue: number;
  tags: string[];
  createdAt: string;
  transactions: Transaction[];
}

export type TaskType = "call" | "site_visit" | "document" | "agreement" | "payment" | "meeting" | "whatsapp";

export interface CrmTask {
  id: string;
  brandId: string;
  title: string;
  type: TaskType;
  dueAt: string;
  status: "open" | "done" | "snoozed";
  assignedTo: string;
  leadId?: string;
  contactId?: string;
  priority: "low" | "normal" | "high";
  /** True when the rules engine created it rather than a person. */
  autoGenerated: boolean;
  /** Which rule fired, so a person can see why the task exists. */
  rule?: string;
  notes?: string;
  completedAt?: string;
  createdAt: string;
}

export const LEAD_STATUSES: Array<{ id: LeadStatus; label: string; color: string }> = [
  { id: "new", label: "New", color: "#8b8b95" },
  { id: "contacted", label: "Contacted", color: "#22d3ee" },
  { id: "site_visit_scheduled", label: "Site Visit Scheduled", color: "#a78bfa" },
  { id: "negotiation", label: "Negotiation", color: "#fbbf24" },
  { id: "booking_token_paid", label: "Booking Token Paid", color: "#f472b6" },
  { id: "won", label: "Won", color: "#34d399" },
  { id: "lost", label: "Lost", color: "#fb7185" },
];

export const SOURCE_LABELS: Record<LeadSource, string> = {
  instagram: "Instagram",
  facebook: "Facebook",
  whatsapp: "WhatsApp",
  meta_ads: "Meta Ads",
  google_ads: "Google Ads",
  portal_99acres: "99acres",
  portal_magicbricks: "MagicBricks",
  portal_housing: "Housing.com",
  referral: "Referral",
  broker: "Broker",
  walk_in: "Walk-in",
  website: "Website",
};

/** Filter bands, in rupees. The floor matches the cheapest inventory. */
export const BUDGET_BANDS = [
  { id: "1.2-3", label: "₹1.2 – 3 Cr", min: 1.2e7, max: 3e7 },
  { id: "3-5", label: "₹3 – 5 Cr", min: 3e7, max: 5e7 },
  { id: "5-10", label: "₹5 – 10 Cr", min: 5e7, max: 1e8 },
  { id: "10-25", label: "₹10 – 25 Cr", min: 1e8, max: 2.5e8 },
  { id: "25+", label: "₹25 Cr+", min: 2.5e8, max: Number.MAX_SAFE_INTEGER },
];

export const KYC_LABELS: Record<KycStatus, string> = {
  not_started: "Not started",
  pending: "Pending",
  verified: "Verified",
  rejected: "Rejected",
};

export const HNWI_LABELS: Record<HnwiTier, string> = {
  none: "Standard",
  affluent: "Affluent",
  hnwi: "HNWI",
  uhnwi: "UHNWI",
};
