import { pageContext } from "@/lib/page-context";
import { TopBar } from "@/components/shell";
import { Stat } from "@/components/ui";
import { TasksList } from "@/components/crm/tasks-list";
import { CrmEmpty } from "../_empty";

export const dynamic = "force-dynamic";

export default async function TasksPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const sp = await searchParams;
  const { db, brand, brandId } = pageContext(sp);
  const tasks = db.crmTasks.filter((t) => t.brandId === brandId);
  const leadNames = Object.fromEntries(db.leads.filter((l) => l.brandId === brandId).map((l) => [l.id, l.name]));
  const hasCrm = db.leads.some((l) => l.brandId === brandId);

  const now = Date.now();
  const overdue = tasks.filter((t) => t.status === "open" && new Date(t.dueAt).getTime() < now);
  const today = tasks.filter((t) => t.status === "open" && new Date(t.dueAt).toDateString() === new Date().toDateString());

  return (
    <>
      <TopBar brands={db.brands} brandId={brandId} title="Tasks" subtitle={`${tasks.filter((t) => t.status === "open").length} open · ${brand.name}`} />
      <div className="space-y-5 p-7">
        {!hasCrm ? (
          <CrmEmpty brandName={brand.name} brandId={brandId} />
        ) : (
          <>
            <div className="grid gap-3 md:grid-cols-4">
              <Stat label="Open" value={String(tasks.filter((t) => t.status === "open").length)} sub="assigned across the team" />
              <Stat label="Overdue" value={String(overdue.length)} sub="past due date" />
              <Stat label="Due today" value={String(today.length)} sub="on the day plan" />
              <Stat label="Auto-generated" value={String(tasks.filter((t) => t.autoGenerated).length)} sub="created by the rules engine" />
            </div>
            <TasksList
              tasks={tasks}
              brandId={brandId}
              leadNames={leadNames}
              title="All tasks"
              hint="Manual and automated, in one list. Automated ones show the rule that created them."
            />
          </>
        )}
      </div>
    </>
  );
}
