import { NextResponse } from "next/server";
import { mutate } from "@/lib/db";
import { uid } from "@/lib/ids";
import type { CrmTask } from "@/lib/crm/types";
import { guard } from "@/lib/auth/guard";

export async function POST(req: Request) {
  const denied = await guard("customers.write");
  if (denied) return denied;

  const body = (await req.json()) as Partial<CrmTask> & { brandId: string; title: string; dueAt: string };
  const task: CrmTask = {
    id: uid("task"),
    brandId: body.brandId,
    title: body.title,
    type: body.type ?? "call",
    dueAt: body.dueAt,
    status: "open",
    assignedTo: body.assignedTo ?? "Unassigned",
    leadId: body.leadId,
    contactId: body.contactId,
    priority: body.priority ?? "normal",
    autoGenerated: false,
    notes: body.notes,
    createdAt: new Date().toISOString(),
  };
  mutate((db) => void db.crmTasks.push(task));
  return NextResponse.json({ ok: true, task });
}

/**
 * Complete or snooze. Completed auto-tasks keep their deterministic id, which is
 * what stops the rules engine from resurrecting something a person closed.
 */
export async function PATCH(req: Request) {
  const denied = await guard("customers.write");
  if (denied) return denied;

  const body = (await req.json()) as { taskId: string; status?: CrmTask["status"]; dueAt?: string };
  const task = mutate((db) => {
    const t = db.crmTasks.find((x) => x.id === body.taskId);
    if (!t) return null;
    if (body.status) {
      t.status = body.status;
      t.completedAt = body.status === "done" ? new Date().toISOString() : undefined;
    }
    if (body.dueAt) t.dueAt = body.dueAt;
    return t;
  });
  if (!task) return NextResponse.json({ ok: false, error: "task not found" }, { status: 404 });
  return NextResponse.json({ ok: true, task });
}
