import { pageContext } from "@/lib/page-context";
import { RULES } from "@/lib/crm/rules";
import { TopBar } from "@/components/shell";
import { Card, SectionTitle, Stat } from "@/components/ui";
import { TasksList } from "@/components/crm/tasks-list";
import { CrmEmpty } from "../_empty";

export const dynamic = "force-dynamic";

/**
 * Follow-ups are the automated slice of tasks, grouped by day so the week reads
 * as a plan rather than a backlog. The rules that generate them are listed on
 * the page, because a reminder system people cannot inspect is one they stop
 * trusting.
 */
export default async function FollowUpsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const sp = await searchParams;
  const { db, brand, brandId } = pageContext(sp);
  const auto = db.crmTasks.filter((t) => t.brandId === brandId && t.autoGenerated);
  const leadNames = Object.fromEntries(db.leads.filter((l) => l.brandId === brandId).map((l) => [l.id, l.name]));
  const hasCrm = db.leads.some((l) => l.brandId === brandId);

  const now = Date.now();
  const week = auto.filter((t) => {
    const d = new Date(t.dueAt).getTime();
    return t.status === "open" && d >= now && d < now + 7 * 86400000;
  });
  const visits = auto.filter((t) => t.type === "site_visit" && t.status === "open");
  const agreements = auto.filter((t) => ["agreement", "document"].includes(t.type) && t.status === "open");

  return (
    <>
      <TopBar brands={db.brands} brandId={brandId} title="Follow-ups" subtitle={`${auto.length} automated reminders · ${brand.name}`} />
      <div className="space-y-5 p-7">
        {!hasCrm ? (
          <CrmEmpty brandName={brand.name} brandId={brandId} />
        ) : (
          <>
            <div className="grid gap-3 md:grid-cols-4">
              <Stat label="Next 7 days" value={String(week.length)} sub="scheduled reminders" />
              <Stat label="Site visits" value={String(visits.length)} sub="confirmations & feedback calls" />
              <Stat label="Agreement & docs" value={String(agreements.length)} sub="drafting, signing, registration" />
              <Stat label="Overdue" value={String(auto.filter((t) => t.status === "open" && new Date(t.dueAt).getTime() < now).length)} sub="needs attention today" />
            </div>

            <TasksList
              tasks={auto}
              brandId={brandId}
              leadNames={leadNames}
              groupByDay
              title="Scheduled follow-ups"
              hint="Generated from lead state. Re-running is safe — nothing you completed comes back."
            />

            <Card>
              <SectionTitle
                title="Rules that generate these"
                hint="Each obligation is implied by a lead's stage, so nobody has to remember it"
              />
              <div className="space-y-2">
                {RULES.map((r) => (
                  <div key={r.id} className="rounded-lg border border-ink-700 p-3">
                    <div className="flex items-center gap-2">
                      <span className="text-[12.5px] font-medium text-mist-100">{r.label}</span>
                      <code className="ml-auto rounded bg-ink-800 px-1.5 py-0.5 text-[10px] text-mist-400">{r.id}</code>
                    </div>
                    <p className="mt-1 text-[11.5px] leading-relaxed text-mist-400">{r.why}</p>
                  </div>
                ))}
              </div>
            </Card>
          </>
        )}
      </div>
    </>
  );
}
